### ISSUE TITLE
Getting "Invalid encoding for parameter"

### ISSUE THREAD

**Issue by denis-kos** [thoughtbot/griddler-sendgrid#37]
Hi,
I'm using griddler to accept incoming email. For some emails which has some non-English characters (like Bosnian language etc.) I'm getting following error. It looks like in most of the cases such emails are coming from Outlook clients (office365). Seems to be working fine with gmail.
I was trying to use [rack-utf8_sanitizer](https://github.com/whitequark/rack-utf8_sanitizer) gem like this:

```ruby
config.middleware.insert 0, Rack::UTF8Sanitizer, sanitizable_content_types: ['multipart/form-data', 'multipart/alternative', 'multipart/mixed'], only: ['rack.input']
```
It works, but if there is an attachment in the email, this breaks it.
If I set `Send Raw` in the SendGrid configuration, the request is coming in fine, but then I don't have a body (as [noted in this gem readme](https://github.com/thoughtbot/griddler-sendgrid#usage))

Any help would be greatly appreciated!

<details>
  <summary>ActionController::BadRequest Invalid request parameters: Invalid encoding for parameter</summary>

```
Rack::QueryParser::InvalidParameterError: Invalid encoding for parameter: <html>
  ...
<div>� Moshe</div>
  ...
</a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr...
  from action_dispatch/request/utils.rb:39:in `check_param_encoding'
  from action_dispatch/request/utils.rb:34:in `block in check_param_encoding'
  from action_dispatch/request/utils.rb:34:in `each_value'
  from action_dispatch/request/utils.rb:34:in `check_param_encoding'
  from action_dispatch/http/request.rb:403:in `block in POST'
  from rack/request.rb:69:in `fetch'
  from rack/request.rb:69:in `fetch_header'
  from action_dispatch/http/request.rb:398:in `POST'
  from action_dispatch/http/parameters.rb:55:in `parameters'
  from action_dispatch/http/filter_parameters.rb:43:in `filtered_parameters'
  from action_controller/metal/instrumentation.rb:24:in `process_action'
  from action_controller/metal/params_wrapper.rb:249:in `process_action'
  from active_record/railties/controller_runtime.rb:27:in `process_action'
  from scout_apm/instruments/action_controller_rails_3_rails4.rb:120:in `process_action'
  from abstract_controller/base.rb:165:in `process'
  from action_view/rendering.rb:39:in `process'
  from action_controller/metal.rb:190:in `dispatch'
  from action_controller/metal.rb:254:in `dispatch'
  from action_dispatch/routing/route_set.rb:50:in `dispatch'
  from action_dispatch/routing/route_set.rb:33:in `serve'
  from action_dispatch/journey/router.rb:50:in `block in serve'
  from action_dispatch/journey/router.rb:32:in `each'
  from action_dispatch/journey/router.rb:32:in `serve'
  from action_dispatch/routing/route_set.rb:842:in `call'
  from scout_apm/instruments/rails_router.rb:29:in `call_with_scout_instruments'
  from scout_apm/middleware.rb:17:in `call'
  from rack/attack.rb:103:in `call'
  from rack/attack.rb:127:in `call'
  from active_record/middleware/database_selector.rb:53:in `block in call'
  from active_record/middleware/database_selector/resolver.rb:71:in `block (2 levels) in write_to_primary'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_record/middleware/database_selector/resolver.rb:70:in `block in write_to_primary'
  from active_record/connection_handling.rb:388:in `with_role_and_shard'
  from active_record/connection_handling.rb:175:in `connected_to'
  from active_record/middleware/database_selector/resolver.rb:69:in `write_to_primary'
  from active_record/middleware/database_selector/resolver.rb:44:in `write'
  from active_record/middleware/database_selector.rb:65:in `select_database'
  from active_record/middleware/database_selector.rb:52:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from rack/tempfile_reaper.rb:15:in `call'
  from rack/etag.rb:27:in `call'
  from rack/conditional_get.rb:40:in `call'
  from rack/head.rb:12:in `call'
  from action_dispatch/http/permissions_policy.rb:22:in `call'
  from action_dispatch/http/content_security_policy.rb:19:in `call'
  from rack/session/abstract/id.rb:266:in `context'
  from rack/session/abstract/id.rb:260:in `call'
  from action_dispatch/middleware/cookies.rb:689:in `call'
  from action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from active_support/callbacks.rb:98:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:29:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from rails/rack/logger.rb:37:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:99:in `block in tagged'
  from active_support/tagged_logging.rb:37:in `tagged'
  from active_support/tagged_logging.rb:99:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from request_store/middleware.rb:19:in `call'
  from action_dispatch/middleware/request_id.rb:26:in `call'
  from rack/method_override.rb:24:in `call'
  from rack/runtime.rb:22:in `call'
  from rails_autoscale_agent/middleware.rb:27:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from action_dispatch/middleware/static.rb:24:in `call'
  from font_assets/middleware.rb:17:in `block in call'
  from font_assets/middleware.rb:40:in `do_request'
  from font_assets/middleware.rb:16:in `call'
  from rack/sendfile.rb:110:in `call'
  from action_dispatch/middleware/ssl.rb:77:in `call'
  from action_dispatch/middleware/host_authorization.rb:142:in `call'
  from rack/cors.rb:100:in `call'
  from rack/utf8_sanitizer.rb:22:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from scout_apm/instruments/middleware_summary.rb:58:in `call'
  from rails/engine.rb:539:in `call'
  from puma/configuration.rb:252:in `call'
  from puma/request.rb:77:in `block in handle_request'
  from puma/thread_pool.rb:340:in `with_force_shutdown'
  from puma/request.rb:76:in `handle_request'
  from puma/server.rb:441:in `process_client'
  from puma/thread_pool.rb:147:in `block in spawn_thread'
  from logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```
</details>

**Comment by denis-kos** [comment]
I suspect this could be due to `iso-8859-1` encoding of the body that is coming from outlook, but not sure how to deal with this.

```
"charsets": "{\"to\":\"UTF-8\",\"html\":\"iso-8859-1\",\"subject\":\"UTF-8\",\"from\":\"UTF-8\",\"text\":\"iso-8859-1\"}",
```

**Comment by denis-kos** [comment]
Thank you @GearoidDC. For now I have switched to [griddler-mailgun](https://github.com/bradpauly/griddler-mailgun) but will try this `skip_parameter_encoding` option.

**Comment by RomainMorlevat** [comment]
Also got the issue with emails forwarded through Outlook.

**Comment by stefannibrasil** [comment]
Closing this as this library has been deprecated: https://github.com/thoughtbot/griddler-sendgrid/pull/41
